# Generated by Django 3.0.7 on 2020-08-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_auto_20200814_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
