# Generated by Django 3.0.7 on 2020-08-21 11:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_delete_orderlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_bag',
            field=jsonfield.fields.JSONField(),
        ),
    ]
