# Generated by Django 3.0.7 on 2020-07-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jumper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumper_Name', models.CharField(max_length=254)),
                ('jumper_Date_Of_Birth', models.DateField()),
            ],
        ),
    ]
