# Generated by Django 3.0.7 on 2020-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200803_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jumper',
            old_name='jumper_Phone_Number',
            new_name='Phone_Number',
        ),
        migrations.AddField(
            model_name='jumper',
            name='Email',
            field=models.EmailField(default='', max_length=40),
        ),
    ]
